// Copyright 2026 printing-press-golden and contributors. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package learn

import (
	"context"
	"database/sql"
	"fmt"
	"sort"
	"strings"
	"time"

	"learn-loop-example-pp-cli/internal/learn/entities"
	"learn-loop-example-pp-cli/internal/learn/patterns"
)

// Default thresholds. Keep in sync with the documented contract in
// SKILL.md: the recall match-score floor is 0.6 (token-set Jaccard)
// and the default result cap is 10.
const (
	defaultJaccardMin    = 0.6
	defaultRecallLimit   = 10
	defaultMinConfidence = 1
)

// SourcePattern marks a Hit synthesized by the pattern substitution
// engine rather than read from search_learnings.
const SourcePattern = "pattern"

// LearningActionBoost mirrors the action string stored in
// search_learnings for a default rerank rule.
const LearningActionBoost = "boost"

// Hit is one row in the recall envelope. Field tags mirror the JSON
// contract agents read.
type Hit struct {
	ResourceID       string     `json:"resource_id"`
	ResourceType     string     `json:"resource_type,omitempty"`
	Venue            string     `json:"venue,omitempty"`
	Action           string     `json:"action"`
	Confidence       int        `json:"confidence"`
	MatchScore       float64    `json:"match_score"`
	EntityMatch      string     `json:"entity_match"`
	ResourceEntities []string   `json:"resource_entities,omitempty"`
	Source           string     `json:"source"`
	LastObservedAt   *time.Time `json:"last_observed_at,omitempty"`
	AliasTarget      string     `json:"alias_target,omitempty"`
	Warnings         []string   `json:"warnings,omitempty"`
}

// Result is the top-level recall envelope. Found mirrors the legacy
// {found, results} shape with additive entity-aware fields.
type Result struct {
	Query         string   `json:"query"`
	Normalized    string   `json:"normalized"`
	QueryEntities []string `json:"query_entities"`
	Found         bool     `json:"found"`
	MatchScore    float64  `json:"match_score,omitempty"`
	Results       []Hit    `json:"results"`
	Mismatches    []Hit    `json:"mismatches,omitempty"`
	Warnings      []string `json:"warnings,omitempty"`
}

// Opts tunes Recall behavior. Zero-value defaults:
//
//	MinConfidence -> 1 (any row)
//	Limit         -> 10
//	JaccardMin    -> 0.6
//	EntityConfig  -> entities.NewConfig() (default English stopwords, no ticker patterns)
//
// DebugMismatches surfaces the mismatches array in the envelope.
// NoLearn short-circuits to an empty envelope.
//
// EntityConfig is the per-CLI entity extractor config built once at
// startup. Carried on Opts rather than positionally so callers that
// don't need per-CLI configuration (legacy prediction-goat lineage,
// future opt-out CLIs) can pass Opts{} and inherit defaults.
//
// ResourceTypeFields maps each resource_type to the ordered list of
// JSON fields ResourceEntitiesFromJSON should read to pull entity
// tokens from a stored resource row. Empty / missing entries leave
// the resource side with no entity signal (partial / unknown).
//
// PatternKinds is the CLI's per-spec list of table-backed lookup
// kinds (from LearnConfig.EntityLookupSeeds) the pattern engine
// should try ahead of the built-in computed kinds.
type Opts struct {
	MinConfidence      int
	Limit              int
	JaccardMin         float64
	DebugMismatches    bool
	NoLearn            bool
	EntityConfig       *entities.Config
	ResourceTypeFields map[string][]string
	PatternKinds       []string
}

// Recall is the entity-aware read path. db is the open *sql.DB
// pointing at the local SQLite store with the v6 learn schema; the
// per-CLI entity extractor config is carried on opts.EntityConfig
// (nil falls back to entities.NewConfig() defaults).
//
// Returns a non-nil Result on every call: cold queries get the
// envelope shape populated with the normalized form and the query
// entities. Errors are reserved for DB-level failures.
func Recall(ctx context.Context, db *sql.DB, query string, opts Opts) (Result, error) {
	cfg := opts.EntityConfig
	if cfg == nil {
		cfg = entities.NewConfig()
	}
	normalized := Normalize(query, cfg)
	result := Result{
		Query:         query,
		Normalized:    normalized.NonEntityNormalized,
		QueryEntities: append([]string(nil), normalized.Entities...),
		Results:       []Hit{},
	}
	if result.QueryEntities == nil {
		result.QueryEntities = []string{}
	}
	if opts.NoLearn {
		return result, nil
	}

	minConf := opts.MinConfidence
	if minConf <= 0 {
		minConf = defaultMinConfidence
	}
	limit := opts.Limit
	if limit <= 0 {
		limit = defaultRecallLimit
	}
	jMin := opts.JaccardMin
	if jMin == 0 {
		jMin = defaultJaccardMin
	}
	if jMin < 0 {
		jMin = 0
	}

	queryTokens := strings.Fields(normalized.NonEntityNormalized)
	if len(queryTokens) == 0 && len(normalized.Entities) == 0 && len(normalized.Tickers) == 0 {
		return result, nil
	}

	rows, err := db.QueryContext(ctx, `SELECT query_pattern, COALESCE(query_entities, ''),
		COALESCE(venue, ''), COALESCE(resource_type, ''), resource_id, action,
		COALESCE(alias_target, ''), source, confidence, created_at, last_observed_at
		FROM search_learnings
		WHERE confidence >= ?`, minConf)
	if err != nil {
		return result, fmt.Errorf("recall query: %w", err)
	}
	defer rows.Close()

	var hits []Hit
	var mismatches []Hit

	for rows.Next() {
		var (
			queryPattern   string
			storedEntities string
			venue          string
			resourceType   string
			resourceID     string
			action         string
			aliasTarget    string
			source         string
			confidence     int
			createdAt      time.Time
			lastObserved   sql.NullTime
		)
		if err := rows.Scan(&queryPattern, &storedEntities, &venue, &resourceType,
			&resourceID, &action, &aliasTarget, &source, &confidence, &createdAt, &lastObserved); err != nil {
			return result, fmt.Errorf("recall scan: %w", err)
		}

		storedNorm := Normalize(queryPattern, cfg)
		score := Jaccard(queryTokens, strings.Fields(storedNorm.NonEntityNormalized))
		if score < jMin {
			continue
		}

		storedEntitySlice, _ := ParseStoredEntities(storedEntities)
		if len(storedEntitySlice) == 0 {
			storedEntitySlice = storedNorm.Entities
		}

		hit := Hit{
			ResourceID:   resourceID,
			ResourceType: resourceType,
			Venue:        venue,
			Action:       action,
			Confidence:   confidence,
			MatchScore:   score,
			Source:       source,
			AliasTarget:  aliasTarget,
		}
		if lastObserved.Valid {
			t := lastObserved.Time
			hit.LastObservedAt = &t
		}
		validateResource(ctx, db, cfg, &hit, normalized.Entities, storedEntitySlice, opts.ResourceTypeFields)
		if hit.EntityMatch == EntityMatchMismatch {
			mismatches = append(mismatches, hit)
		} else {
			hits = append(hits, hit)
		}
	}
	if err := rows.Err(); err != nil {
		return result, fmt.Errorf("recall rows: %w", err)
	}

	// Generalization layer: ask the pattern engine whether any template
	// applies to this query. Errors are swallowed; pattern hits are
	// additive on top of direct hits.
	patternHits, _ := patterns.Apply(ctx, db, query, normalized.NonEntityNormalized, normalized.Entities, patterns.Opts{
		JaccardMin:      jMin,
		Limit:           limit,
		AdditionalKinds: opts.PatternKinds,
	})
	if len(patternHits) > 0 {
		existing := make(map[string]struct{}, len(hits))
		for _, h := range hits {
			existing[hitKey(h.ResourceType, h.ResourceID)] = struct{}{}
		}
		for _, ph := range patternHits {
			key := hitKey(ph.ResourceType, ph.ResourceID)
			if _, dup := existing[key]; dup {
				continue
			}
			existing[key] = struct{}{}
			hits = append(hits, Hit{
				ResourceID:       ph.ResourceID,
				ResourceType:     ph.ResourceType,
				Venue:            ph.Venue,
				Action:           LearningActionBoost,
				Confidence:       ph.Confidence,
				MatchScore:       ph.MatchScore,
				EntityMatch:      EntityMatchExact,
				ResourceEntities: ph.ResourceEntities,
				Source:           SourcePattern,
				LastObservedAt:   ph.LastObservedAt,
			})
		}
	}

	sortHits(hits)
	sortHits(mismatches)

	if len(hits) > limit {
		hits = hits[:limit]
	}
	if len(mismatches) > limit {
		mismatches = mismatches[:limit]
	}

	if hits == nil {
		result.Results = []Hit{}
	} else {
		result.Results = hits
	}
	if opts.DebugMismatches {
		if mismatches == nil {
			result.Mismatches = []Hit{}
		} else {
			result.Mismatches = mismatches
		}
	}
	result.Found = len(hits) > 0
	if result.Found {
		result.MatchScore = hits[0].MatchScore
	}

	if !result.Found && len(mismatches) == 0 {
		result.Warnings = append(result.Warnings, TopWarningNoLearningsForQueryFamily)
	}

	return result, nil
}

func validateResource(ctx context.Context, db *sql.DB, cfg *entities.Config, hit *Hit, queryEntities, storedEntitySlice []string, fieldsByType map[string][]string) {
	var data string
	err := db.QueryRowContext(ctx,
		`SELECT data FROM resources WHERE resource_type = ? AND id = ?`,
		hit.ResourceType, hit.ResourceID,
	).Scan(&data)
	if err != nil {
		hit.Warnings = append(hit.Warnings, WarningResourceNotInStore)
		hit.EntityMatch = ClassifyEntityMatch(queryEntities, storedEntitySlice)
		if hit.EntityMatch == EntityMatchPartial && len(queryEntities) == 0 && len(storedEntitySlice) == 0 {
			hit.EntityMatch = EntityMatchUnknown
		}
		addLowConfidenceWarning(hit)
		return
	}
	var fields []string
	if fieldsByType != nil {
		fields = fieldsByType[hit.ResourceType]
	}
	resourceEntities := ResourceEntitiesFromJSON([]byte(data), fields, cfg)
	hit.ResourceEntities = resourceEntities
	hit.EntityMatch = ClassifyEntityMatch(queryEntities, resourceEntities)
	addLowConfidenceWarning(hit)
}

func addLowConfidenceWarning(hit *Hit) {
	if hit.Confidence < 2 {
		hit.Warnings = append(hit.Warnings, WarningLowConfidence)
	}
}

func sortHits(hits []Hit) {
	sort.SliceStable(hits, func(i, j int) bool {
		pi := entityMatchPriority(hits[i].EntityMatch)
		pj := entityMatchPriority(hits[j].EntityMatch)
		if pi != pj {
			return pi < pj
		}
		si := sourcePriority(hits[i].Source)
		sj := sourcePriority(hits[j].Source)
		if si != sj {
			return si < sj
		}
		if hits[i].Confidence != hits[j].Confidence {
			return hits[i].Confidence > hits[j].Confidence
		}
		if hits[i].MatchScore != hits[j].MatchScore {
			return hits[i].MatchScore > hits[j].MatchScore
		}
		ai := time.Time{}
		aj := time.Time{}
		if hits[i].LastObservedAt != nil {
			ai = *hits[i].LastObservedAt
		}
		if hits[j].LastObservedAt != nil {
			aj = *hits[j].LastObservedAt
		}
		return ai.After(aj)
	})
}

func sourcePriority(source string) int {
	if source == SourcePattern {
		return 1
	}
	return 0
}

func hitKey(resourceType, resourceID string) string {
	return resourceType + "|" + resourceID
}

func entityMatchPriority(em string) int {
	switch em {
	case EntityMatchExact:
		return 0
	case EntityMatchPartial:
		return 1
	case EntityMatchUnknown:
		return 2
	case EntityMatchMismatch:
		return 3
	default:
		return 4
	}
}
