// Copyright 2026 test-org. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package client

import (
	"encoding/json"
	"net/http"
)

type Client struct {
	BaseURL    string
	HTTPClient *http.Client
}

// Hand-added by an operator: custom trace-header injector. This represents
// the kind of pre-existing user edit that regen-merge must preserve when
// it applies the new short-circuit block in fresh.
func (c *Client) customAnnotateRequest(req *http.Request) {
	req.Header.Set("X-Custom-Trace", "operator-edit-2026")
}

func (c *Client) do(method, path string) (json.RawMessage, int, error) {
	return nil, 0, nil
}
