// Copyright 2026 test-org. Licensed under Apache-2.0. See LICENSE.
// Generated by CLI Printing Press (https://github.com/mvanhorn/cli-printing-press). DO NOT EDIT.

package client

import (
	"encoding/json"
	"net/http"
)

type Client struct {
	BaseURL    string
	HTTPClient *http.Client
}

// isMutatingVerb covers the four mutating HTTP verbs, used by the
// verify-mode short-circuit gate.
func isMutatingVerb(method string) bool {
	switch method {
	case "DELETE", "POST", "PUT", "PATCH":
		return true
	}
	return false
}

// verifyShortCircuitEnvelope mints the synthetic verify-mode response.
func verifyShortCircuitEnvelope(method, path string) json.RawMessage {
	body := map[string]any{
		"__pp_verify_synthetic__": true,
		"status":                  "noop",
		"reason":                  "verify_short_circuit",
		"method":                  method,
		"path":                    path,
	}
	b, _ := json.Marshal(body)
	return b
}

func (c *Client) do(method, path string) (json.RawMessage, int, error) {
	// New short-circuit block under verify mode.
	return nil, 0, nil
}
